version: "3.9"

services:
  slackbot:
    image: slackbot
    container_name: slackbot
    restart: unless-stopped

    environment:
      SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
      SLACK_CHANNEL: ${SLACK_CHANNEL}
      IMAGE_PATH: /data/example.png
      TZ: America/New_York

    volumes:
      - ./images:/data # <Host>:<Container>
      - ./cron.env:/app/cron.env:ro

